### PR TITLE
Returning if the leader statefulset is being deleted

### LINKED ISSUE #732: LWS controller will create a revision connected to a StatefulSet that is being deleted
**What happened**:
When quickly deleting an LWS instance and creating it again, the controller will create a revision for a StatefulSet that is being deleted. This is due to the statefulset taking a while to be deleted, so when the controller checks the leader Sts here https://github.com/kubernetes-sigs/lws/blob/main/pkg/controllers/leaderworkerset_controller.go#L111, it will find the statefulset that corresponds to the previews LWS object. 

**What you expected to happen**:
Wait for the leader Sts to be deleted before attempting to create a new controller revision.

**How to reproduce it (as minimally and precisely as possible)**:
Create an LWS instance, delete it and immediately create it again.

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
- LWS version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by Edwinhr716**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes

Fixes #732 

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: pkg/controllers/leaderworkerset_controller.go [hunk 1]
```diff
@@ -114,6 +114,10 @@ func (r *LeaderWorkerSetReconciler) Reconcile(ctx context.Context, req ctrl.Requ
 		return ctrl.Result{}, err
 	}
 
+	if leaderSts.DeletionTimestamp != nil {
+		return ctrl.Result{}, nil
+	}
+
```
Comment (ahg-g) [inline pkg/controllers/leaderworkerset_controller.go:121]: What will trigger a reconcile again?

Comment (Edwinhr716) [reply pkg/controllers/leaderworkerset_controller.go:121]: Added a requeue request

File: pkg/controllers/leaderworkerset_controller.go [hunk 2]
```diff
@@ -114,6 +114,10 @@ func (r *LeaderWorkerSetReconciler) Reconcile(ctx context.Context, req ctrl.Requ
 		return ctrl.Result{}, err
 	}
 
+	if leaderSts != nil && leaderSts.DeletionTimestamp != nil {
+		return ctrl.Result{Requeue: true}, nil
```
Comment (ahg-g) [inline pkg/controllers/leaderworkerset_controller.go]: I would use requeueAfter and give it like 5 seconds

Comment (Edwinhr716) [reply pkg/controllers/leaderworkerset_controller.go]: Changed
