### PR TITLE
Fix UpdateInProgress conditions for newly created LWS

### LINKED ISSUE #400: Create a new lws or modify replicas, UpdateInProgress will also exist in conditions
**What happened**:
I am adapting lws in volcano, and when adapting the rolling update scenario, I determine whether an lws is in a rolling update based on the presence of an UpdateInProgress condition set to True in the lws. However, now when I create a new lws, I find that sometimes the UpdateInProgress condition is also stably generated, which does not match the description of this condition:
```
// LeaderWorkerSetUpdateInProgress means lws is performing a rolling update. UpdateInProgress
// is true when the lws is in upgrade process after the (leader/worker) template is updated. If only replicas is modified, it will
// not be considered as UpdateInProgress.
LeaderWorkerSetUpdateInProgress LeaderWorkerSetConditionType = "UpdateInProgress"
```
When creating a new lws or modifying replicas, this condition should not occur, but currently I can basically reproduce this situation, especially repeatedly creating and deleting the same lws should be able to stably reproduce it

**What you expected to happen**:
When creating a new lws or modifying replicas, this condition should not occur

**How to reproduce it (as minimally and precisely as possible)**:
My lws yaml:
```
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: leaderworkerset-rollout
spec:
  rolloutStrategy:
    type: RollingUpdate
    rollingUpdateConfiguration:
      maxSurge: 2
  replicas: 4
  leaderWorkerTemplate:
    size: 4
    workerTemplate:
      metadata:
        name: worker    
      spec:
        containers:
        - name: nginx
          image: nginx:1.14.2
          resources:
            limits:
              cpu: "100m"
            requests:
              cpu: "50m"
          ports:
          - containerPort: 8080
```

**Anything else we need to know?**:
Especially repeatedly creating and deleting the same lws should be able to stably reproduce it

**Environment**:

- Kubernetes version (use `kubectl version`): v1.31
- LWS version (use `git describe --tags --dirty --always`): v0.5.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by yankay**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it

**Fixes #400**  

**Bug Scenario**:  
A condition occurs where the LWS worker StatefulSet has not yet been properly initialized.  

**Root Cause**:  
In  https://github.com/kubernetes-sigs/lws/pull/298/files#diff-636763c4aab72861dbe05856e71e11abf551830d79fdcd848f3133ffc9c2d6e1R386 , the introduction of the `continue` keyword causes `currentNonBurstWorkerCount++` to execute prematurely.  

This leads to the condition `updatedNonBurstWorkerCount < currentNonBurstWorkerCount` at https://github.com/kubernetes-sigs/lws/blob/v0.6.0/pkg/controllers/leaderworkerset_controller.go#L441 , triggering the bug.  

**Fix**:  
Simply move `currentNonBurstWorkerCount++` **below** the `continue` statement to resolve the issue.  

#### Does this PR introduce a user-facing change?

```release-note
Fix UpdateInProgress conditions for newly created LWS
```

### CODE REVIEW

**Comment by Edwinhr716** [comment]
Thanks for taking a look! Would it be possible to add an integration/unit test to cover this test case?

**Comment by yankay** [comment]
> Thanks for taking a look! Would it be possible to add an integration/unit test to cover this bug?

HI @Edwinhr716 

A test case has been added :-)

File: test/integration/controllers/leaderworkerset_test.go [hunk 1]
```diff
@@ -464,6 +464,26 @@ var _ = ginkgo.Describe("LeaderWorkerSet controller", func() {
...
 		}),
+		ginkgo.Entry("Ensure UpdateInProgress condition is not set during LWS initialization", &testCase{
+			makeLeaderWorkerSet: func(nsName string) *wrappers.LeaderWorkerSetWrapper {
+				return wrappers.BuildLeaderWorkerSet(nsName).Replica(4).MaxSurge(2)
+			},
+			updates: []*update{
+				{
+					checkLWSState: func(lws *leaderworkerset.LeaderWorkerSet) {
+						testing.ExpectLeaderWorkerSetProgressing(ctx, k8sClient, lws, "Replicas are progressing")
+						gomega.Expect(func() error {
```
Comment (Edwinhr716) [inline test/integration/controllers/leaderworkerset_test.go:475]: Why not use this function instead? https://github.com/kubernetes-sigs/lws/blob/370b8692a62ed6135d70c6a944b3be78a043312c/test/testutils/validators.go#L387

File: test/integration/controllers/leaderworkerset_test.go [hunk 2]
```diff
@@ -464,6 +464,26 @@ var _ = ginkgo.Describe("LeaderWorkerSet controller", func() {
 				},
 			},
 		}),
+		ginkgo.Entry("Ensure UpdateInProgress condition is not set during LWS initialization", &testCase{
```
Comment (Edwinhr716) [inline test/integration/controllers/leaderworkerset_test.go:467]: Does this test fail without the fix?

File: test/integration/controllers/leaderworkerset_test.go (hunk 1 above)
Comment (yankay) [reply test/integration/controllers/leaderworkerset_test.go:475]: HI @Edwinhr716 

In `ExpectLeaderWorkerSetNoUpgradeInProgress`, `CheckLeaderWorkerSetHasCondition` is designed to verify the presence of the UpdateInProgress condition.
However, the expected behavior is that the `UpdateInProgress condition` ​​should not exist yet​​, so the check will fail (timeout error) and cause the test to fail.

This is why we need this code segment—to explicitly handle this validation.

File: test/integration/controllers/leaderworkerset_test.go (hunk 2 above)
Comment (yankay) [reply test/integration/controllers/leaderworkerset_test.go:467]: When the fix is not applied, the test will fail. Below is a screenshot of the error:

img_v3_02l6_70f49207-0347-4b85-bed9-7ffc93cb1aag

File: test/integration/controllers/leaderworkerset_test.go (hunk 1 above)
Comment (Edwinhr716) [reply test/integration/controllers/leaderworkerset_test.go:475]: That makes sense

File: test/integration/controllers/leaderworkerset_test.go (hunk 2 above)
Comment (Edwinhr716) [reply test/integration/controllers/leaderworkerset_test.go:467]: Thanks
