### PR TITLE
Validate partition field be non-negative

### LINKED ISSUE #615: The partition number should not bigger than the replicas setting
**What happened**:
When I set the partition bigger than the replicas, no warning , no prompt message , should we add validation to check the value of partition field.

  replicas: 6
  rolloutStrategy:
    rollingUpdateConfiguration:
      maxSurge: 0
      maxUnavailable: 2
      partition: 10
    type: RollingUpdate

**What you expected to happen**:
Add validation to check the value of partition field.

**How to reproduce it (as minimally and precisely as possible)**:
always

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`): v1.33.3
- LWS version (use `git describe --tags --dirty --always`): 0.7
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by LuyuZhang00**
#### What this PR does / why we need it
When  user sets partition while creating a lws, they will receive the following warnings/errors:
•​​partition < 0​​: Error; creation is rejected.
partition and maxsurge will be ignored during creation

#### Which issue(s) this PR fixes

Fixes #615 

#### Does this PR introduce a user-facing change?

NONE

### CODE REVIEW

**Comment by LuyuZhang00** [comment]
cc @ardaguclu @kerthcet

File: pkg/webhooks/leaderworkerset_webhook_test.go [hunk 1]
```diff
@@ -184,3 +188,124 @@ func TestIsNotMoreThan100Percent(t *testing.T) {
 		})
 	}
 }
+
+func TestPartitionValidation(t *testing.T) {
```
Comment (Edwinhr716) [inline pkg/webhooks/leaderworkerset_webhook_test.go]: We use integration tests to test that validation is working as intended, see https://github.com/kubernetes-sigs/lws/blob/main/test/integration/webhooks/leaderworkerset_test.go#L184. Please write an test there instead.

**Comment by Edwinhr716** [comment]
Thanks for the quick fix!

File: pkg/webhooks/leaderworkerset_webhook_test.go (hunk 1 above)
Comment (LuyuZhang00) [reply pkg/webhooks/leaderworkerset_webhook_test.go]: thanks, I have updated it! @Edwinhr716

File: pkg/webhooks/leaderworkerset_webhook.go [hunk 2]
```diff
@@ -151,6 +174,19 @@ func (r *LeaderWorkerSetWebhook) generalValidate(obj runtime.Object) field.Error
...
+		// Validate partition value
+		partition := lws.Spec.RolloutStrategy.RollingUpdateConfiguration.Partition
+		partitionPath := specPath.Child("rolloutStrategy", "rollingUpdateConfiguration", "partition")
+		if partition != nil {
+			if *partition < 0 {
+				allErrs = append(allErrs, field.Invalid(partitionPath, *partition, "partition must be greater than or equal to 0"))
+			}
+			if *partition > *lws.Spec.Replicas {
+				allErrs = append(allErrs, field.Invalid(partitionPath, *partition,
+					fmt.Sprintf("partition must be less than or equal to replicas %d", *lws.Spec.Replicas)))
```
Comment (yankay) [inline pkg/webhooks/leaderworkerset_webhook.go]: HI @LuyuZhang00 

By analogy, in a StatefulSet, it is acceptable to set it this way: "If a StatefulSet's .spec.updateStrategy.rollingUpdate.partition is greater than its .spec.replicas, updates to its .spec.template will not be propagated to its Pods." (Reference: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#partitions)

Therefore, "partition greater than replicas" should not be considered a bug.
How do you think about that?

Comment (LuyuZhang00) [reply pkg/webhooks/leaderworkerset_webhook.go]: @yankay thanks! To maintain consistency with the StatefulSet, I have refined it. Please check!

File: pkg/webhooks/leaderworkerset_webhook.go [hunk 3]
```diff
@@ -94,8 +94,33 @@ var _ webhook.CustomValidator = &LeaderWorkerSetWebhook{}
...
+	lws := obj.(*v1.LeaderWorkerSet)
+	warnings := admission.Warnings{}
+
+	if lws.Spec.RolloutStrategy.RollingUpdateConfiguration != nil {
+		partition := lws.Spec.RolloutStrategy.RollingUpdateConfiguration.Partition
+		maxSurge := lws.Spec.RolloutStrategy.RollingUpdateConfiguration.MaxSurge
+		replicas := *lws.Spec.Replicas
+
+		// Warn users that partition/maxSurge will be ignored during initial deployment
+		if partition != nil && *partition > 0 {
```
Comment (kerthcet) [inline pkg/webhooks/leaderworkerset_webhook.go]: Should we add this to warning? I think warning is something 1) when we got unexpected behaviors, 2) or potential performance problems 3) or some unrecommended usages. Here this is working as expected.

File: pkg/webhooks/leaderworkerset_webhook.go [hunk 4]
```diff
@@ -228,7 +261,7 @@ func getPercentValue(intOrStringValue intstr.IntOrString) (int, bool) {
 func validateNonnegativeField(value int64, fldPath *field.Path) field.ErrorList {
 	allErrs := field.ErrorList{}
 	if value < 0 {
-		allErrs = append(allErrs, field.Invalid(fldPath, value, "must be grater than or equal to 0"))
+		allErrs = append(allErrs, field.Invalid(fldPath, value, "must be greater than or equal to 0"))
```
Comment (kerthcet) [inline pkg/webhooks/leaderworkerset_webhook.go:239]: Good catch.

File: pkg/webhooks/leaderworkerset_webhook.go [hunk 5]
```diff
@@ -159,6 +184,14 @@ func (r *LeaderWorkerSetWebhook) generalValidate(obj runtime.Object) field.Error
 		allErrs = append(allErrs, validatePositiveIntOrPercent(maxSurge, maxSurgePath)...)
 		allErrs = append(allErrs, isNotMoreThan100Percent(maxSurge, maxSurgePath)...)
 	}
+
+	// Validate partition value
+	partition := lws.Spec.RolloutStrategy.RollingUpdateConfiguration.Partition
+	partitionPath := specPath.Child("rolloutStrategy", "rollingUpdateConfiguration", "partition")
+	if lws.Spec.RolloutStrategy.RollingUpdateConfiguration != nil {
```
Comment (kerthcet) [inline pkg/webhooks/leaderworkerset_webhook.go:163]: If this is nil, L189 will panic, move the code to this block please.

File: pkg/webhooks/leaderworkerset_webhook.go (hunk 3 above)
Comment (kerthcet) [reply pkg/webhooks/leaderworkerset_webhook.go]: Does sts or deployment has this warning? If not, let's remove it.

**Review by kerthcet — COMMENTED** [review]
/lgtm
/approve
/label tide/merge-method-squash

Thanks @LuyuZhang00
