### PR TITLE
Fix infinite StatefulSet creation loops by validate leader annotations

### LINKED ISSUE #385: Is it inappropriate to mark leaderworkerset.SetNameLabelKey here?
I think there are incorrect labels, which cause the worker nodes to continuously increase until the names of the pods exceed the limit.

v0.5.1
1、pkg\controllers\pod_controller.go
```
283 func constructWorkerStatefulSetApplyConfiguration
...
**306 		leaderworkerset.SetNameLabelKey:         lws.Name,**
```
As a result, the label "leaderworkerset.sigs.k8s.io/name" is added to the worker pods.

2、 pkg\webhooks\pod_webhook.go
```
82  func (p *PodWebhook) Default
...
90 	// if pod is not part of leaderworkerset, skip
91	_, found := pod.Labels[leaderworkerset.SetNameLabelKey]
92	if !found {
93		return nil
94	}
...
140  _, workerIndex := statefulsetutils.GetParentNameAndOrdinal(pod.Name)  ##--> workerIndex =0
...
**144 pod.Labels[leaderworkerset.WorkerIndexLabelKey] = fmt.Sprint(workerIndex)**
```
Then, a label "leaderworkerset.sigs.k8s.io/worker-index: '0'" is added to the worker pods, making them the leader pods.

3、pkg\controllers\pod_controller.go
```
66   func (r *PodReconciler) Reconcile
...
96 	// worker pods' reconciliation is only done to handle restart policy
97	if !podutils.LeaderPod(pod) {
98		return ctrl.Result{}, nil
99	}
```
Here, the process won't be skipped. Instead, new worker pods will continue to be created, and the process goes back to step 1.

----
I'm not sure if my understanding is correct. 
If my understanding is incorrect, please ignore it.

### LINKED ISSUE #390: lws generated replicas is incorrect
I use kubeflow generate distributed-serving job,one master and one work but create 12 pods:

```
arena serve distributed \
 --name=vllm \
 --version=alpha \
 --restful-port=5000 \
 --image=vllm/vllm-openai:latest \
 --data=pvc-model:/mnt/models \
 --masters=1 \
 --replicas=1 \
 --max-surge=1 \
 --master-gpus=1 \
 --master-command="ray start --head --port=6379; vllm serve /mnt/models/Qwen2-1.5B --port 5000 --dtype half --pipeline-parallel-size 2" \
 --workers=1 \
 --worker-gpus=1 \
 --worker-command="ray start --address=\$(MASTER_ADDR):6379 --block" \
 --share-memory=4Gi \
 --startup-probe-action=httpGet \
 --startup-probe-action-option="path: /health" \
 --startup-probe-action-option="port: 5000" \
 --startup-probe-option="periodSeconds: 60" \
 --startup-probe-option="failureThreshold: 5"
```
kubectl get pod output:
```
vllm-alpha-distributed-serving-0                             0/1     Running             0          10s
vllm-alpha-distributed-serving-0-0                           1/1     Running             0          10s
vllm-alpha-distributed-serving-0-0-0                         0/1     ContainerCreating   0          10s
vllm-alpha-distributed-serving-0-0-0-0                       0/1     ContainerCreating   0          10s
vllm-alpha-distributed-serving-0-0-0-0-0                     0/1     ContainerCreating   0          10s
vllm-alpha-distributed-serving-0-0-0-0-0-0                   0/1     ContainerCreating   0          10s
vllm-alpha-distributed-serving-0-0-0-0-0-0-0                 0/1     ContainerCreating   0          10s
vllm-alpha-distributed-serving-0-0-0-0-0-0-0-0               0/1     Pending             0          10s
vllm-alpha-distributed-serving-0-0-0-0-0-0-0-0-0             0/1     Pending             0          10s
vllm-alpha-distributed-serving-0-0-0-0-0-0-0-0-0-0           0/1     Pending             0          10s
vllm-alpha-distributed-serving-0-0-0-0-0-0-0-0-0-0-0         0/1     Pending             0          9s
vllm-alpha-distributed-serving-0-0-0-0-0-0-0-0-0-0-0-0       0/1     Pending             0          9s

```
 kubectl get LeaderWorkerSet vllm-alpha-distributed-serving -o yaml output:
```
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  annotations:
    helm.sh/created: "1739759061"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"leaderworkerset.x-k8s.io/v1","kind":"LeaderWorkerSet","metadata":{"annotations":{"helm.sh/created":"1739759061"},"labels":{"app":"distributed-serving","arena.kubeflow.org/uid":"3399d840e8b371ed7ca45dda29debeb1","chart":"distributed-serving-0.1.0","heritage":"Helm","release":"vllm-alpha","serviceName":"vllm","servingName":"vllm","servingType":"distributed-serving","servingVersion":"alpha"},"name":"vllm-alpha-distributed-serving","namespace":"default"},"spec":{"leaderWorkerTemplate":{"leaderTemplate":{"metadata":{"annotations":{"arena.kubeflow.org/username":"kubecfg:certauth:admin"},"labels":{"app":"distributed-serving","arena.kubeflow.org/uid":"3399d840e8b371ed7ca45dda29debeb1","chart":"distributed-serving-0.1.0","heritage":"Helm","release":"vllm-alpha","role":"master","serviceName":"vllm","servingName":"vllm","servingType":"distributed-serving","servingVersion":"alpha"}},"spec":{"containers":[{"command":["sh","-c","ray start --head --port=6379; vllm serve /mnt/models/Qwen2-1.5B --port 5000 --dtype half --pipeline-parallel-size 2"],"env":[{"name":"MASTER_ADDR","value":"$(LWS_LEADER_ADDRESS)"},{"name":"WORLD_SIZE","valueFrom":{"fieldRef":{"fieldPath":"metadata.annotations['leaderworkerset.sigs.k8s.io/size']"}}},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"POD_INDEX","valueFrom":{"fieldRef":{"fieldPath":"metadata.labels['leaderworkerset.sigs.k8s.io/worker-index']"}}},{"name":"GROUP_INDEX","valueFrom":{"fieldRef":{"fieldPath":"metadata.labels['leaderworkerset.sigs.k8s.io/group-index']"}}},{"name":"GPU_COUNT","value":"1"},{"name":"HOSTFILE","value":"/etc/hostfile"},{"name":"ROLE","value":"master"}],"image":"harbor.hzxingzai.cn/tools/vllm/vllm-openai:latest","imagePullPolicy":"IfNotPresent","name":"distributed-serving-master","ports":[{"containerPort":5000,"name":"restful","protocol":"TCP"}],"resources":{"limits":{"nvidia.com/gpu":1}},"startupProbe":{"failureThreshold":5,"httpGet":{"path":"/health","port":5000},"periodSeconds":60},"volumeMounts":[{"mountPath":"/dev/shm","name":"dshm"},{"mountPath":"/mnt/models","name":"pvc-model"},{"mountPath":"/etc/hostfile","name":"vllm-alpha-cm","subPathExpr":"hostfile-$(GROUP_INDEX)"}]}],"volumes":[{"configMap":{"items":[{"key":"hostfile-0","mode":438,"path":"hostfile-0"}],"name":"vllm-alpha-cm"},"name":"vllm-alpha-cm"},{"emptyDir":{"medium":"Memory","sizeLimit":"4Gi"},"name":"dshm"},{"name":"pvc-model","persistentVolumeClaim":{"claimName":"pvc-model"}}]}},"restartPolicy":"RecreateGroupOnPodRestart","size":2,"workerTemplate":{"metadata":{"annotations":{"arena.kubeflow.org/username":"kubecfg:certauth:admin"},"labels":{"app":"distributed-serving","chart":"distributed-serving-0.1.0","heritage":"Helm","release":"vllm-alpha","role":"worker","serviceName":"vllm","servingName":"vllm","servingType":"distributed-serving","servingVersion":"alpha"}},"spec":{"containers":[{"command":["sh","-c","ray start --address=$(MASTER_ADDR):6379 --block"],"env":[{"name":"MASTER_ADDR","value":"$(LWS_LEADER_ADDRESS)"},{"name":"WORLD_SIZE","valueFrom":{"fieldRef":{"fieldPath":"metadata.annotations['leaderworkerset.sigs.k8s.io/size']"}}},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"POD_INDEX","valueFrom":{"fieldRef":{"fieldPath":"metadata.labels['leaderworkerset.sigs.k8s.io/worker-index']"}}},{"name":"GROUP_INDEX","valueFrom":{"fieldRef":{"fieldPath":"metadata.labels['leaderworkerset.sigs.k8s.io/group-index']"}}},{"name":"GPU_COUNT","value":"1"},{"name":"HOSTFILE","value":"/etc/hostfile"},{"name":"ROLE","value":"worker"}],"image":"harbor.hzxingzai.cn/tools/vllm/vllm-openai:latest","imagePullPolicy":"IfNotPresent","name":"distributed-serving-worker","resources":{"limits":{"nvidia.com/gpu":1}},"volumeMounts":[{"mountPath":"/dev/shm","name":"dshm"},{"mountPath":"/mnt/models","name":"pvc-model"},{"mountPath":"/etc/hostfile","name":"vllm-alpha-cm","subPathExpr":"hostfile-$(GROUP_INDEX)"}]}],"volumes":[{"configMap":{"items":[{"key":"hostfile-0","mode":438,"path":"hostfile-0"}],"name":"vllm-alpha-cm"},"name":"vllm-alpha-cm"},{"emptyDir":{"medium":"Memory","sizeLimit":"4Gi"},"name":"dshm"},{"name":"pvc-model","persistentVolumeClaim":{"claimName":"pvc-model"}}]}}},"replicas":1,"rolloutStrategy":{"rollingUpdateConfiguration":{"maxSurge":1}}}}
  creationTimestamp: "2025-02-17T02:24:23Z"
  generation: 1
  labels:
    app: distributed-serving
    arena.kubeflow.org/uid: 3399d840e8b371ed7ca45dda29debeb1
    chart: distributed-serving-0.1.0
    heritage: Helm
    release: vllm-alpha
    serviceName: vllm
    servingName: vllm
    servingType: distributed-serving
    servingVersion: alpha
  name: vllm-alpha-distributed-serving
  namespace: default
  resourceVersion: "236644878"
  uid: 4f73c906-ef17-4ec4-9a0b-50ef3c9076a5
spec:
  leaderWorkerTemplate:
    leaderTemplate:
      metadata:
        annotations:
          arena.kubeflow.org/username: kubecfg:certauth:admin
        labels:
          app: distributed-serving
          arena.kubeflow.org/uid: 3399d840e8b371ed7ca45dda29debeb1
          chart: distributed-serving-0.1.0
          heritage: Helm
          release: vllm-alpha
          role: master
          serviceName: vllm
          servingName: vllm
          servingType: distributed-serving
          servingVersion: alpha
      spec:
        containers:
        - command:
          - sh
          - -c
          - ray start --head --port=6379; vllm serve /mnt/models/Qwen2-1.5B --port
            5000 --dtype half --pipeline-parallel-size 2
          env:
          - name: MASTER_ADDR
            value: $(LWS_LEADER_ADDRESS)
          - name: WORLD_SIZE
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['leaderworkerset.sigs.k8s.io/size']
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_INDEX
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['leaderworkerset.sigs.k8s.io/worker-index']
          - name: GROUP_INDEX
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['leaderworkerset.sigs.k8s.io/group-index']
          - name: GPU_COUNT
            value: "1"
          - name: HOSTFILE
            value: /etc/hostfile
          - name: ROLE
            value: master
          image: vllm/vllm-openai:latest
          imagePullPolicy: IfNotPresent
          name: distributed-serving-master
          ports:
          - containerPort: 5000
            name: restful
            protocol: TCP
          resources:
            limits:
              nvidia.com/gpu: "1"
          startupProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: 5000
            periodSeconds: 60
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /mnt/models
            name: pvc-model
          - mountPath: /etc/hostfile
            name: vllm-alpha-cm
            subPathExpr: hostfile-$(GROUP_INDEX)
        volumes:
        - configMap:
            items:
            - key: hostfile-0
              mode: 438
              path: hostfile-0
            name: vllm-alpha-cm
          name: vllm-alpha-cm
        - emptyDir:
            medium: Memory
            sizeLimit: 4Gi
          name: dshm
        - name: pvc-model
          persistentVolumeClaim:
            claimName: pvc-model
    restartPolicy: RecreateGroupOnPodRestart
    size: 2
    workerTemplate:
      metadata:
        annotations:
          arena.kubeflow.org/username: kubecfg:certauth:admin
        labels:
          app: distributed-serving
          chart: distributed-serving-0.1.0
          heritage: Helm
          release: vllm-alpha
          role: worker
          serviceName: vllm
          servingName: vllm
          servingType: distributed-serving
          servingVersion: alpha
      spec:
        containers:
        - command:
          - sh
          - -c
          - ray start --address=$(MASTER_ADDR):6379 --block
          env:
          - name: MASTER_ADDR
            value: $(LWS_LEADER_ADDRESS)
          - name: WORLD_SIZE
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['leaderworkerset.sigs.k8s.io/size']
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_INDEX
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['leaderworkerset.sigs.k8s.io/worker-index']
          - name: GROUP_INDEX
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['leaderworkerset.sigs.k8s.io/group-index']
          - name: GPU_COUNT
            value: "1"
          - name: HOSTFILE
            value: /etc/hostfile
          - name: ROLE
            value: worker
          image: vllm/vllm-openai:latest
          imagePullPolicy: IfNotPresent
          name: distributed-serving-worker
          resources:
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /mnt/models
            name: pvc-model
          - mountPath: /etc/hostfile
            name: vllm-alpha-cm
            subPathExpr: hostfile-$(GROUP_INDEX)
        volumes:
        - configMap:
            items:
            - key: hostfile-0
              mode: 438
              path: hostfile-0
            name: vllm-alpha-cm
          name: vllm-alpha-cm
        - emptyDir:
            medium: Memory
            sizeLimit: 4Gi
          name: dshm
        - name: pvc-model
          persistentVolumeClaim:
            claimName: pvc-model
  networkConfig:
    subdomainPolicy: Shared
  replicas: 1
  rolloutStrategy:
    rollingUpdateConfiguration:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  startupPolicy: LeaderCreated
status:
  conditions:
  - lastTransitionTime: "2025-02-17T02:24:31Z"
    message: Replicas are progressing
    reason: GroupsProgressing
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-02-17T02:24:23Z"
    message: Rolling Upgrade is in progress
    reason: GroupsUpdating
    status: "False"
    type: UpdateInProgress
  - lastTransitionTime: "2025-02-17T02:24:30Z"
    message: All replicas are ready
    reason: AllGroupsReady
    status: "False"
    type: Available
  hpaPodSelector: leaderworkerset.sigs.k8s.io/name=vllm-alpha-distributed-serving,leaderworkerset.sigs.k8s.io/worker-index=0
  readyReplicas: 5
  replicas: 1
  updatedReplicas: 12
```

### LINKED ISSUE #391: lws controller cannot reconcile the pod to the right status
**What happened**:
lws controller cannot reconcile the pod to the right status

```
kubectl apply -f deepseek-lws.yaml
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: sglang
  namespace: sg-system
  labels:
    app: sglang
spec:
  replicas: 1
  startupPolicy: LeaderCreated
  rolloutStrategy:
    type: RollingUpdate
    rollingUpdateConfiguration:
      maxSurge: 0
      maxUnavailable: 2
  leaderWorkerTemplate:
    size: 2
    restartPolicy: RecreateGroupOnPodRestart
    leaderTemplate:
      metadata:
        labels:
          role: leader
      spec:
        containers:
          - name: sglang-head
            image: ccr.ccs.tencentyun.com/kason/sglang:v0.4.2.post4-cu125
            imagePullPolicy: IfNotPresent
            workingDir: /sgl-workspace
            command: ["sh", "-c"]
            args:
            - >
              cd /sgl-workspace && python3 -m sglang.launch_server
              --model-path /root/.cache/modelscope/DeepSeek-R1
              --served-model-name deepseek-r1
              --tp 16
              --dist-init-addr $LWS_LEADER_ADDRESS:20000
              --nnodes $LWS_GROUP_SIZE
              --node-rank 0
              --trust-remote-code
              --context-length 131072
              --enable-metrics
              --host 0.0.0.0
              --port 8000
            env:
              - name: GLOO_SOCKET_IFNAME
                value: eth0
              - name: NCCL_IB_HCA
                value: "mlx5_0,mlx5_1,mlx5_4,mlx5_5"
              - name: NCCL_P2P_LEVEL
                value: "NVL"
              - name: NCCL_IB_GID_INDEX
                value: "0"
              - name: NCCL_IB_CUDA_SUPPORT
                value: "1"
              - name: NCCL_IB_DISABLE
                value: "0"
              - name: NCCL_SOCKET_IFNAME
                value: "eth0"
                #value: "ibs13,ibs11,ibs15,ibs17"
              - name: NCCL_DEBUG
                value: "INFO"
              - name: NCCL_NET_GDR_LEVEL
                value: "2"
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: SGLANG_USE_MODELSCOPE
                value: "true"
            ports:
            - containerPort: 8000
              name: http
              protocol: TCP
            - containerPort: 20000
              name: distributed
              protocol: TCP
            resources:
              limits:
                cpu: "128"
                memory: "1Ti"
                nvidia.com/gpu: "8"
                rdma/ib: "4"
              requests:
                cpu: "128"
                memory: "1Ti"
                nvidia.com/gpu: "8"
                rdma/ib: "4"
            securityContext:
              capabilities:
                add:
                - IPC_LOCK
                - SYS_PTRACE
            volumeMounts:
              - mountPath: /root/.cache/modelscope
                name: modelscope-cache
              - mountPath: /dev/shm
                name: shm-volume
              - name: localtime
                mountPath: /etc/localtime
                readOnly: true
            readinessProbe:
              tcpSocket:
                port: 8000
              initialDelaySeconds: 120
              periodSeconds: 30
        volumes:
          - name: modelscope-cache
            hostPath:
              path: /file_CPU_01/modelServing
          - name: shm-volume
            emptyDir:
              sizeLimit: 512Gi
              medium: Memory
          - name: localtime
            hostPath:
              path: /etc/localtime
              type: File
        schedulerName: volcano
    workerTemplate:
      metadata:
        name: sglang-worker
      spec:
        containers:
          - name: sglang-worker
            image: ccr.ccs.tencentyun.com/kason/sglang:v0.4.2.post4-cu125
            imagePullPolicy: IfNotPresent
            workingDir: /sgl-workspace
            command: ["sh", "-c"]
            args:
            - >
              cd /sgl-workspace && python3 -m sglang.launch_server
              --model-path /home/bmm-system/data/ckpt/deepseek/DeepSeek-R1
              --served-model-name deepseek-r1
              --tp 16
              --dist-init-addr $LWS_LEADER_ADDRESS:20000
              --nnodes $LWS_GROUP_SIZE
              --node-rank $LWS_WORKER_INDEX
              --trust-remote-code
              --context-length 131072
              --enable-metrics
              --host 0.0.0.0
              --port 8000
            env:
              - name: GLOO_SOCKET_IFNAME
                value: eth0
              - name: NCCL_IB_HCA
                value: "mlx5_0,mlx5_1,mlx5_4,mlx5_5"
              - name: NCCL_P2P_LEVEL
                value: "NVL"
              - name: NCCL_IB_GID_INDEX
                value: "0"
              - name: NCCL_IB_CUDA_SUPPORT
                value: "1"
              - name: NCCL_IB_DISABLE
                value: "0"
              - name: NCCL_SOCKET_IFNAME
                value: "eth0"
                #value: "ibs13,ibs11,ibs15,ibs17"
              - name: NCCL_DEBUG
                value: "INFO"
              - name: NCCL_NET_GDR_LEVEL
                value: "2"
              - name: SGLANG_USE_MODELSCOPE
                value: "true"
              - name: LWS_WORKER_INDEX
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['leaderworkerset.sigs.k8s.io/worker-index']
            ports:
            - containerPort: 8000
              name: http
              protocol: TCP
            - containerPort: 20000
              name: distributed
              protocol: TCP
            resources:
              limits:
                cpu: "128"
                memory: "1Ti"
                nvidia.com/gpu: "8"
                rdma/ib: "4"
              requests:
                cpu: "128"
                memory: "1Ti"
                nvidia.com/gpu: "8"
                rdma/ib: "4"
            securityContext:
              capabilities:
                add:
                - IPC_LOCK
                - SYS_PTRACE
            volumeMounts:
            - mountPath: /root/.cache/modelscope
              name: modelscope-cache
            - mountPath: /dev/shm
              name: shm-volume
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
        nodeSelector:
          glm.ai/app: infer
        volumes:
        - name: modelscope-cache
          hostPath:
            path: /file_CPU_01/modelServing
        - name: shm-volume
          emptyDir:
            sizeLimit: 512Gi
            medium: Memory
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
        schedulerName: volcano

```

Image

```
Status:
  Conditions:
    Last Transition Time:  2025-02-17T12:31:55Z
    Message:               Replicas are progressing
    Reason:                GroupsProgressing
    Status:                True
    Type:                  Progressing
  Hpa Pod Selector:        leaderworkerset.sigs.k8s.io/name=sglang,leaderworkerset.sigs.k8s.io/worker-index=0
  Replicas:                1
  Updated Replicas:        24
Events:
  Type    Reason             Age                 From             Message
  ----    ------             ----                ----             -------
  Normal  CreatingRevision   36s                 leaderworkerset  Creating revision with key 7c7756fcbb for a newly created LeaderWorkerSet
  Normal  GroupsProgressing  36s                 leaderworkerset  Created leader statefulset sglang
  Normal  GroupsProgressing  36s (x2 over 36s)   leaderworkerset  Replicas are progressing, with 0 groups ready of total 1 groups
  Normal  GroupsProgressing  36s                 leaderworkerset  Created worker statefulset for leader pod sglang-0
  Normal  GroupsProgressing  36s                 leaderworkerset  Created worker statefulset for leader pod sglang-0-0
  Normal  GroupsProgressing  36s                 leaderworkerset  Created worker statefulset for leader pod sglang-0-0-0
  Normal  GroupsProgressing  36s                 leaderworkerset  Created worker statefulset for leader pod sglang-0-0-0-0
  Normal  GroupsProgressing  36s                 leaderworkerset  Created worker statefulset for leader pod sglang-0-0-0-0-0
  Normal  GroupsProgressing  36s                 leaderworkerset  Created worker statefulset for leader pod sglang-0-0-0-0-0-0
  Normal  GroupsProgressing  36s                 leaderworkerset  Created worker statefulset for leader pod sglang-0-0-0-0-0-0-0
  Normal  GroupsUpdating     36s                 leaderworkerset  Rolling Upgrade is in progress, with 0 groups ready of total 1 groups
  Normal  GroupsProgressing  33s (x13 over 36s)  leaderworkerset  (combined from similar events): Created worker statefulset for leader pod sglang-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0
```

**What you expected to happen**:

Image

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
- LWS version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by yankay**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it

When running on Kubernetes clusters <1.27 without the StatefulSetStartOrdinal feature gate enabled, LeaderWorkerSet controllers enter infinite reconciliation loops that exhaust cluster resources.

So the PR is to block infinite reconciliation loops caused by missing Kubernetes version checks when StatefulSetStartOrdinal isn't enabled (clusters <1.27).

#### Which issue(s) this PR fixes

Fixes #391
Fixes #385
Fixes #390

#### Does this PR introduce a user-facing change?

```release-note
Fix infinite StatefulSet creation loops by validate leader annotations
```

### CODE REVIEW

**Comment by yankay** [comment]
HI @Edwinhr716 @kerthcet 

Would you please help to review it.

File: pkg/controllers/pod_controller.go [hunk 1]
```diff
@@ -98,6 +98,15 @@ func (r *PodReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.R
 		return ctrl.Result{}, nil
 	}
 
+	// validate leader annotations to prevent infinite StatefulSet creation loops
+	// see issue: https://github.com/kubernetes-sigs/lws/issues/391
+	if pod.Annotations[leaderworkerset.LeaderPodNameAnnotationKey] != "" {
```
Comment (ahg-g) [inline pkg/controllers/pod_controller.go:103]: I think we should log an error, emit an event with the error. 

However, returning an error is not useful here since it will put the leader pod back into the workerqueue, which means it will get reconciled again and again forever, so I think we should not return an error here and in the error message we log, we should say that we are giving up on reconciling the pod.

Comment (yankay) [reply pkg/controllers/pod_controller.go:103]: Thanks @ahg-g 

It has been changed :-)

**Review by kerthcet — COMMENTED** [review]
/lgtm
/approve

Thanks @yankay

**Comment by yankay** [comment]
Thanks @ahg-g  @kerthcet for the PR review :-)
